[package]
authors = { workspace = true }
description = "Paseo variant of Asset Hub parachain runtime"
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
name = "passet-hub-runtime"
repository = { workspace = true }
version = { workspace = true }

[lints]
workspace = true

[build-dependencies]
substrate-wasm-builder = { version = "30.0.0", optional = true, workspace = true, default-features = true }

[dependencies]
assets-common = { version = "0.26.0", workspace = true }
bp-asset-hub-rococo = { version = "0.22.0", workspace = true }
bp-asset-hub-westend = { version = "0.21.0", workspace = true }
bp-bridge-hub-rococo = { version = "0.26.0", workspace = true }
bp-bridge-hub-westend = { version = "0.22.0", workspace = true }
codec = { features = [ "derive", "max-encoded-len" ], workspace = true }
cumulus-pallet-aura-ext = { version = "0.24.0", workspace = true }
cumulus-pallet-parachain-system = { version = "0.24.0", workspace = true }
cumulus-pallet-session-benchmarking = { version = "25.0.0", workspace = true }
cumulus-pallet-weight-reclaim = { version = "0.6.0", workspace = true }
cumulus-pallet-xcm = { version = "0.23.0", workspace = true }
cumulus-pallet-xcmp-queue = { version = "0.24.0", features = [ "bridging" ], workspace = true }
cumulus-primitives-aura = { version = "0.19.0", workspace = true }
cumulus-primitives-core = { version = "0.22.0", workspace = true }
cumulus-primitives-utility = { version = "0.24.0", workspace = true }
frame-benchmarking = { version = "44.0.0", workspace = true }
frame-executive = { version = "44.0.0", workspace = true }
frame-metadata-hash-extension = { version = "0.12.0", workspace = true }
frame-support = { version = "44.0.0", workspace = true }
frame-system = { version = "44.0.0", workspace = true }
frame-system-benchmarking = { version = "44.0.0", workspace = true }
frame-system-rpc-runtime-api = { version = "38.0.0", workspace = true }
frame-try-runtime = { version = "0.50.0", workspace = true }
hex-literal = { workspace = true, default-features = true }
log = { workspace = true }
pallet-asset-conversion = { version = "26.0.0", workspace = true }
pallet-asset-conversion-ops = { version = "0.12.0", workspace = true }
pallet-asset-conversion-tx-payment = { version = "26.0.0", workspace = true }
pallet-asset-rewards = { version = "0.6.0", workspace = true }
pallet-assets = { version = "47.0.0", workspace = true }
pallet-assets-precompiles = { version = "0.3.0", workspace = true }
pallet-assets-freezer = { version = "0.12.0", workspace = true }
pallet-aura = { version = "43.0.0", workspace = true }
pallet-authorship = { version = "44.0.0", workspace = true }
pallet-balances = { version = "45.0.0", workspace = true }
pallet-collator-selection = { version = "25.0.0", workspace = true }
pallet-message-queue = { version = "47.0.0", workspace = true }
pallet-migrations = { version = "14.0.0", workspace = true }
pallet-multisig = { version = "44.0.0", workspace = true }
pallet-nft-fractionalization = { version = "28.0.0", workspace = true }
pallet-nfts = { version = "38.0.0", workspace = true }
pallet-nfts-runtime-api = { version = "28.0.0", workspace = true }
pallet-proxy = { version = "44.0.0", workspace = true }
pallet-revive = { version = "0.11.0", workspace = true }
pallet-session = { version = "44.0.0", workspace = true }
pallet-state-trie-migration = { version = "49.0.0", workspace = true }
pallet-sudo = { version = "44.0.0", workspace = true }
pallet-timestamp = { version = "43.0.0", workspace = true }
pallet-transaction-payment = { version = "44.0.0", workspace = true }
pallet-transaction-payment-rpc-runtime-api = { version = "44.0.0", workspace = true }
pallet-uniques = { version = "44.0.0", workspace = true }
pallet-utility = { version = "44.0.0", workspace = true }
pallet-xcm = { version = "24.0.0", workspace = true }
pallet-xcm-precompiles = { version = "0.2.0", workspace = true }
pallet-xcm-benchmarks = { version = "24.0.0", workspace = true }
pallet-xcm-bridge-hub-router = { version = "0.22.0", workspace = true }
parachain-info = { workspace = true }
parachains-common = { version = "26.0.0", workspace = true }
polkadot-core-primitives = { version = "19.0.0", workspace = true }
polkadot-parachain-primitives = { version = "18.0.0", workspace = true }
polkadot-primitives = { version = "20.0.0", workspace = true }
polkadot-runtime-common = { version = "23.0.0", workspace = true }
primitive-types = { features = [
	"codec",
	"num-traits",
	"scale-info",
], workspace = true }
scale-info = { features = [ "derive" ], workspace = true }
serde_json = { features = [ "alloc" ], workspace = true }
smallvec = { workspace = true, default-features = true }
snowbridge-inbound-queue-primitives = { version = "0.6.0", workspace = true }
snowbridge-outbound-queue-primitives = { version = "0.6.0", workspace = true }
snowbridge-pallet-system-frontend = { version = "0.6.0", workspace = true }
snowbridge-runtime-common = { version = "0.18.0", workspace = true }
sp-api = { version = "38.0.0", workspace = true }
sp-block-builder = { version = "38.0.0", workspace = true }
sp-consensus-aura = { version = "0.44.0", workspace = true }
sp-core = { version = "38.0.1", workspace = true }
sp-genesis-builder = { version = "0.19.0", workspace = true }
sp-inherents = { version = "38.0.0", workspace = true }
sp-io = { version = "42.0.0", workspace = true }
sp-keyring = { version = "43.0.0", workspace = true }
sp-offchain = { version = "38.0.0", workspace = true }
sp-runtime = { version = "43.0.0", workspace = true }
sp-session = { version = "40.0.0", workspace = true }
sp-std = { version = "14.0.0", workspace = true }
sp-storage = { version = "22.0.0", workspace = true }
sp-transaction-pool = { version = "38.0.0", workspace = true }
sp-version = { version = "41.0.0", workspace = true }
xcm = { workspace = true }
xcm-builder = { workspace = true }
xcm-executor = { workspace = true }
xcm-runtime-apis = { version = "0.11.0", workspace = true }

[dev-dependencies]
asset-test-utils = { version = "28.0.0", default-features = true, workspace = true }
parachains-runtimes-test-utils = { version = "27.0.0", default-features = true, workspace = true }

[features]
default = [ "std" ]
fast-runtime = [  ]
runtime-benchmarks = [
	"assets-common/runtime-benchmarks",
	"cumulus-pallet-parachain-system/runtime-benchmarks",
	"cumulus-pallet-session-benchmarking/runtime-benchmarks",
	"cumulus-pallet-weight-reclaim/runtime-benchmarks",
	"cumulus-pallet-xcmp-queue/runtime-benchmarks",
	"cumulus-primitives-core/runtime-benchmarks",
	"cumulus-primitives-utility/runtime-benchmarks",
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system-benchmarking/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-asset-conversion-ops/runtime-benchmarks",
	"pallet-asset-conversion-tx-payment/runtime-benchmarks",
	"pallet-asset-conversion/runtime-benchmarks",
	"pallet-asset-rewards/runtime-benchmarks",
	"pallet-assets-freezer/runtime-benchmarks",
	"pallet-assets/runtime-benchmarks",
	"pallet-assets-precompiles/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-collator-selection/runtime-benchmarks",
	"pallet-message-queue/runtime-benchmarks",
	"pallet-migrations/runtime-benchmarks",
	"pallet-multisig/runtime-benchmarks",
	"pallet-nft-fractionalization/runtime-benchmarks",
	"pallet-nfts/runtime-benchmarks",
	"pallet-proxy/runtime-benchmarks",
	"pallet-revive/runtime-benchmarks",
	"pallet-state-trie-migration/runtime-benchmarks",
	"pallet-sudo/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"pallet-transaction-payment/runtime-benchmarks",
	"pallet-uniques/runtime-benchmarks",
	"pallet-utility/runtime-benchmarks",
	"pallet-xcm-benchmarks/runtime-benchmarks",
	"pallet-xcm-bridge-hub-router/runtime-benchmarks",
	"pallet-xcm/runtime-benchmarks",
	"pallet-xcm-precompiles/runtime-benchmarks",
	"parachains-common/runtime-benchmarks",
	"polkadot-parachain-primitives/runtime-benchmarks",
	"polkadot-runtime-common/runtime-benchmarks",
	"snowbridge-inbound-queue-primitives/runtime-benchmarks",
	"snowbridge-pallet-system-frontend/runtime-benchmarks",
	"snowbridge-runtime-common/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"xcm-builder/runtime-benchmarks",
	"xcm-executor/runtime-benchmarks",
	"xcm-runtime-apis/runtime-benchmarks",
	"xcm/runtime-benchmarks",
]
std = [
	"assets-common/std",
	"bp-asset-hub-rococo/std",
	"bp-asset-hub-westend/std",
	"bp-bridge-hub-rococo/std",
	"bp-bridge-hub-westend/std",
	"codec/std",
	"cumulus-pallet-aura-ext/std",
	"cumulus-pallet-parachain-system/std",
	"cumulus-pallet-session-benchmarking/std",
	"cumulus-pallet-weight-reclaim/std",
	"cumulus-pallet-xcm/std",
	"cumulus-pallet-xcmp-queue/std",
	"cumulus-primitives-aura/std",
	"cumulus-primitives-core/std",
	"cumulus-primitives-utility/std",
	"frame-benchmarking/std",
	"frame-executive/std",
	"frame-metadata-hash-extension/std",
	"frame-support/std",
	"frame-system-benchmarking/std",
	"frame-system-rpc-runtime-api/std",
	"frame-system/std",
	"frame-try-runtime/std",
	"log/std",
	"pallet-asset-conversion-ops/std",
	"pallet-asset-conversion-tx-payment/std",
	"pallet-asset-conversion/std",
	"pallet-asset-rewards/std",
	"pallet-assets-freezer/std",
	"pallet-assets/std",
	"pallet-assets-precompiles/std",
	"pallet-aura/std",
	"pallet-authorship/std",
	"pallet-balances/std",
	"pallet-collator-selection/std",
	"pallet-message-queue/std",
	"pallet-migrations/std",
	"pallet-multisig/std",
	"pallet-nft-fractionalization/std",
	"pallet-nfts-runtime-api/std",
	"pallet-nfts/std",
	"pallet-proxy/std",
	"pallet-revive/std",
	"pallet-session/std",
	"pallet-state-trie-migration/std",
	"pallet-sudo/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-transaction-payment/std",
	"pallet-uniques/std",
	"pallet-utility/std",
	"pallet-xcm-benchmarks/std",
	"pallet-xcm-bridge-hub-router/std",
	"pallet-xcm/std",
	"pallet-xcm-precompiles/std",
	"parachain-info/std",
	"parachains-common/std",
	"polkadot-core-primitives/std",
	"polkadot-parachain-primitives/std",
	"polkadot-primitives/std",
	"polkadot-runtime-common/std",
	"primitive-types/std",
	"scale-info/std",
	"serde_json/std",
	"snowbridge-inbound-queue-primitives/std",
	"snowbridge-outbound-queue-primitives/std",
	"snowbridge-pallet-system-frontend/std",
	"snowbridge-runtime-common/std",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-consensus-aura/std",
	"sp-core/std",
	"sp-genesis-builder/std",
	"sp-inherents/std",
	"sp-io/std",
	"sp-keyring/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-storage/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"substrate-wasm-builder",
	"xcm-builder/std",
	"xcm-executor/std",
	"xcm-runtime-apis/std",
	"xcm/std",
]
try-runtime = [
	"cumulus-pallet-aura-ext/try-runtime",
	"cumulus-pallet-parachain-system/try-runtime",
	"cumulus-pallet-weight-reclaim/try-runtime",
	"cumulus-pallet-xcm/try-runtime",
	"cumulus-pallet-xcmp-queue/try-runtime",
	"frame-executive/try-runtime",
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"frame-try-runtime/try-runtime",
	"pallet-asset-conversion-ops/try-runtime",
	"pallet-asset-conversion-tx-payment/try-runtime",
	"pallet-asset-conversion/try-runtime",
	"pallet-asset-rewards/try-runtime",
	"pallet-assets-freezer/try-runtime",
	"pallet-assets/try-runtime",
	"pallet-assets-precompiles/try-runtime",
	"pallet-aura/try-runtime",
	"pallet-authorship/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-collator-selection/try-runtime",
	"pallet-message-queue/try-runtime",
	"pallet-migrations/try-runtime",
	"pallet-multisig/try-runtime",
	"pallet-nft-fractionalization/try-runtime",
	"pallet-nfts/try-runtime",
	"pallet-proxy/try-runtime",
	"pallet-revive/try-runtime",
	"pallet-session/try-runtime",
	"pallet-state-trie-migration/try-runtime",
	"pallet-sudo/try-runtime",
	"pallet-timestamp/try-runtime",
	"pallet-transaction-payment/try-runtime",
	"pallet-uniques/try-runtime",
	"pallet-utility/try-runtime",
	"pallet-xcm-bridge-hub-router/try-runtime",
	"pallet-xcm/try-runtime",
	"pallet-xcm-precompiles/try-runtime",
	"parachain-info/try-runtime",
	"polkadot-runtime-common/try-runtime",
	"snowbridge-pallet-system-frontend/try-runtime",
	"snowbridge-runtime-common/try-runtime",
	"sp-runtime/try-runtime",
]

# Enable the metadata hash generation in the wasm builder.
metadata-hash = [ "substrate-wasm-builder/metadata-hash" ]

# A feature that should be enabled when the runtime should be built for on-chain
# deployment. This will disable stuff that shouldn't be part of the on-chain wasm
# to make it smaller, like logging for example.
on-chain-release-build = [
	"metadata-hash",
	"sp-api/disable-logging",
]